name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Rebuild node modules (optional)
        run: npm rebuild

      - name: Run linter
        run: ./node_modules/.bin/eslint . --ext .js

      - name: Build Docker image
        run: docker build -t elissia/node-hello .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push elissia/node-hello